apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80

    - name: logger-container
      image: busybox:latest
      command:
        [
          "sh",
          "-c",
          'while true; do echo "$(date -u +%Y-%m-%dT%H:%M:%SZ) - Acesso ao servidor Nginx" >> /var/log/nginx/access.log; sleep 5; done',
        ]
      volumeMounts:
        - name: log-volume
          mountPath: /var/log/nginx

  volumes:
    - name: log-volume
      emptyDir: {}
