apiVersion: v1
kind: PersistentVolume
metadata:
  name: meu-pv
  labels:
    app: minha-aplicacao
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: meu-storageclass
  hostPath:
    path: /data/meu-pv
