apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod
spec:
  containers:
    - name: my-container
      image: nginx:latest
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /index.html
          port: 80
        initialDelaySeconds: 15
        periodSeconds: 10
        timeoutSeconds: 5 # Novo: Define o tempo limite da sonda para 5 segundos
        failureThreshold: 3 # Novo: Define o limite de falhas para 3
