apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx # Substitua pelo rótulo apropriado que corresponde aos seus pods NGINX
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
